version: '3'

services:
  orion:
    image: fiware/orion:2.4.0
    ports:
      - "1026:1026"
    networks:
      - fiware
    command: -dbhost mongo:27017 -logLevel DEBUG -dbTimeout 10000

  iotagent-json:
    image: fiware/iotagent-json:1.14.0
    depends_on:
      - orion
    ports:
      - "4041:4041"
      - "7896:7896"
    networks:
      - fiware
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_TIMESTAMP=true
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_MONGO_HOST=mongo
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentjson
      - IOTA_NORTH_PORT=4041
      - IOTA_PROVIDER_URL=http://iotagent-json:4041
      - IOTA_HTTP_PORT=7896
      - IOTA_LOG_LEVEL=DEBUG

  amqp10-converter:
    image: roboticbase/amqp10-converter:0.2.0
    depends_on:
      - orion
      - iotagent-json
    networks:
      - fiware
    env_file: .env
    environment:
      - AMQP_HOST=${AMQP_HOST}
      - AMQP_PORT=${AMQP_PORT}
      - AMQP_USE_TLS=${AMQP_USE_TLS}
      - AMQP_USERNAME=${AMQP_USERNAME}
      - AMQP_PASSWORD=${AMQP_PASSWORD}
      - IOTA_HOST=iotagent-json
      - IOTA_MANAGE_PORT=4041
      - IOTA_DATA_PORT=7896
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_CB_NGSI_VERSION=v2
      - FIWARE_SERVICE=demoservice
      - FIWARE_SERVICEPATH=/demo/path
      - ENTITIES=[{"type":"robot","id":"robot01"}]
      - SCHEMA_PATHS=["/opt/schema/attr.schema.json","/opt/schema/cmdexe.schema.json"]
      - LOG_LEVEL=DEBUG
    volumes:
      - ./schema/attr.schema.json:/opt/schema/attr.schema.json
      - ./schema/cmdexe.schema.json:/opt/schema/cmdexe.schema.json

networks:
  fiware:
    external:
      name: example_fiware
